version: "3"
services:
  monapp:
    image: python_image:1.0
    depends_on: 
      - db
    networks: 
      - my_network
    environment:
      CSV_FILENAME: "data.csv"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "yolo57"
      POSTGRES_DB: "postgres"
  db:
    image: postgres
    networks: 
      - my_network
    environment:
      POSTGRES_PASSWORD: "yolo57"

networks:
  my_network: