version: "3"
services:
  manager:
    build:
      context: "/"
      dockerfile: "dockerfile"
    image: manager:latest
    depends_on: 
      - db
    networks: 
      - my_network
  db:
    image: postgres
    networks: 
      - my_network
    environment:
      POSTGRES_PASSWORD: "yolo57"

networks:
  my_network: